### PR TITLE
mpl2: improve convergence

### LINKED ISSUE #5884: [ERROR MPL-0040] Failed on cluster frontend/bpd/banked_predictors_0/btb
### Describe the bug

This worked previously with same area, just a tiny change to the behavioral logic of one mocked SRAM: https://github.com/The-OpenROAD-Project/megaboom/pull/135

untar https://drive.google.com/file/d/1AAwT9JdsLzWdspQP576nefa9m780JfiQ/view?usp=drive_link

```
./run-me-BoomTile-asap7-base.sh
```

```
Floorplan Outline: (0.0, 0.0) (2300.0, 2300.0),  Core Outline: (1.026, 1.08) (2297.97, 2297.97)
	Number of std cell instances: 1771752
	Area of std cell instances: 223780.94
	Number of macros: 70
	Area of macros: 485727.16
	Halo width: 19.00
	Halo height: 19.00
	Area of macros with halos: 1065893.00
	Area of std cell instances + Area of macros: 709508.12
	Core area: 5275827.50
	Design Utilization: 0.13
	Core Utilization: 0.05
	Manufacturing Grid: 1

[ERROR MPL-0040] Failed on cluster frontend/bpd/banked_predictors_0/btb
Error: macro_place_util.tcl, 83 MPL-0040
```

### Expected Behavior

No error

### Environment

```shell
OpenROAD v2.0-16257-g81b545063
```

### To Reproduce

See above

### Relevant log output

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolves #5884

This PR is the proper fix for #5655, that's the reason why it also reverts #5799.

Changes:
1. Keep the lowest cost valid result as SA goes so that, if the lowest cost result is not valid we use the former.
2. Minor cleanup

### CODE REVIEW

File: src/mpl2/src/SimulatedAnnealingCore.cpp [hunk 1]
```diff
@@ -569,16 +568,28 @@ void SimulatedAnnealingCore<T>::fastSA()
...
+  }
+
   while (step <= max_num_step_) {
     for (int i = 0; i < num_perturb_per_step_; i++) {
       perturb();
       cost = calNormCost();
+
+      if (cost < pre_cost && isValid()) {
+        updateBestValidResult(best_valid_result);
+      }
```
Comment (maliberty) [inline src/mpl2/src/SimulatedAnnealingCore.cpp:591]: Its possible you have no valid result so far and while `cost < pre_cost` is false it is a valid result.  This will not record it.

Comment (AcKoucher) [reply src/mpl2/src/SimulatedAnnealingCore.cpp]: I'll push a change to ensure we also check if the best result is empty.

**Comment by AcKoucher** [comment]
@oharboe With these changes (on the top of the version you used in #5884) I got:
Screenshot from 2024-10-09 19-28-42

**Review by maliberty — APPROVED** [review]

**Comment by AcKoucher** [comment]
Running secure-CI

**Comment by maliberty** [comment]
Did secure-CI pass?

**Comment by AcKoucher** [comment]
@maliberty It did.
