### PR TITLE
gui: use a buffer to store report text to avoid slowing down OR when logging in Scripting

### LINKED ISSUE #5340: script output display is very slow when the gui is on
### Describe the bug

I've noticed a slowness in gui which is very annoying. It seems this comes from the console input & output.

Using the following procedure:

    proc measure_time {} {
        set TIME_start [clock clicks -milliseconds]
        for {set i 0} {$i < 100} {incr i} {
            puts "Iteration $i"
        }
        set TIME_taken [expr [clock clicks -milliseconds] - $TIME_start]
        puts "Duration $TIME_taken ms"
    }

Without gui the script takes less that 1 ms.

With gui (-gui option or gui::show), it takes 40 ms.
    - source the script takes less that 1 ms whenever it is called.

This is another specific condition in gui that show the slowness with the procedure taking 8 ms.

Basically after link_design is called, all subsequent commands before you get the prompt again are horribly slow.

So basically a script test.tcl ending by run by openroad -gui test.tcl :

    measure_time => 40 ms
    link_design test
    measure_time => 8 s

Once the prompt is available calling again measure_time will takes 40 ms

Now commenting these 3 lines and start again, executing these 3 commands one by one => 40 ms

Same with 3 commands called in a row will give 40 ms followed by 8 s.

### Expected Behavior

Should be few.

### Environment

```shell
OpenROAD 74da93a32ce0cb78d8d93ca473121b8cdd52ff8d from openroad-2024-06-11 package
```

### To Reproduce

openroad -gui test.tcl

test.tcl:

    proc measure_time {} {
        set TIME_start [clock clicks -milliseconds]
        for {set i 0} {$i < 100} {incr i} {
            puts "Iteration $i"
        }
        set TIME_taken [expr [clock clicks -milliseconds] - $TIME_start]
        puts "Duration $TIME_taken ms"
    }
    ....
    measure_time
    link_design test
    measure_time

I'm trying to make a test case. It does not seem easy as using a simpler design does not show the issue.

### Relevant log output

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolve #5340

### CODE REVIEW

**Comment by maliberty** [comment]
@gadfort this is an attempt to speed up the GUI output window when there is a lot of fast scrolling output.  I believe you've used the timer trick elsewhere and would like your input.

**Comment by oharboe** [comment]
@jeffng-or Perhaps this will speed up loading `make gui_route` on megaboom too?

File: src/gui/src/scriptWidget.cpp [hunk 1]
```diff
@@ -115,6 +116,10 @@ ScriptWidget::ScriptWidget(QWidget* parent)
           &ScriptWidget::outputChanged);
   connect(pauser_, &QPushButton::pressed, this, &ScriptWidget::pauserClicked);
   connect(pause_timer_.get(), &QTimer::timeout, this, &ScriptWidget::unpause);
+  connect(report_timer_.get(),
+          &QTimer::timeout,
+          this,
+          &ScriptWidget::flushReportBufferToOuput);
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:122]: you should also connect this to `commandFinishedExecuting` to avoid a delay in printing the output.

File: src/gui/src/scriptWidget.cpp [hunk 2]
```diff
@@ -208,9 +225,19 @@ void ScriptWidget::addLogToOutput(const QString& text, const QColor& color)
   addToOutput(text, color);
 }
 
-void ScriptWidget::addReportToOutput(const QString& text)
+bool ScriptWidget::reportTimerIsActive()
+{
+  return report_timer_->isActive();
+}
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:231]: this might be a overkill since the single line of code it wraps is fairly self-explanatory. (this is a stylistic thing, so nothing major here)

File: src/gui/src/scriptWidget.cpp [hunk 3]
```diff
@@ -385,8 +412,15 @@ class ScriptWidget::GuiSink : public spdlog::sinks::base_sink<Mutex>
         std::string(formatted.data(), formatted.size()));
 
     if (msg.level == spdlog::level::level_enum::off) {
-      // this comes from a ->report
-      widget_->addReportToOutput(formatted_msg);
+      if (!widget_->reportTimerIsActive()) {
+        widget_->startReportTimer();
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:416]: this can only be started from the main thread, you need to guard against this. otherwise you will get a bunch of errors about this timer.

File: src/gui/src/scriptWidget.cpp [hunk 4]
```diff
@@ -125,6 +130,18 @@ ScriptWidget::ScriptWidget(QWidget* parent)
   setWidget(container);
 }
 
+// When displaying text in Scripting, processing events in order to
+// ensure the text is visible to the user can considerably slow down
+// the logging, so, for reports, we use a buffer.
+void ScriptWidget::flushReportBufferToOuput()
+{
+  report_timer_->stop();
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:138]: not sure if you need to do this.

File: src/gui/src/scriptWidget.cpp [hunk 5]
```diff
@@ -125,6 +130,18 @@ ScriptWidget::ScriptWidget(QWidget* parent)
...
+
+  // this comes from a ->report
+  addTextToOutput(report_buffer_, buffer_msg_);
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:141]: you might want to check if the buffer has anything before calling this

File: src/gui/src/scriptWidget.cpp [hunk 6]
```diff
@@ -125,6 +130,18 @@ ScriptWidget::ScriptWidget(QWidget* parent)
...
+  report_buffer_.clear();
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:142]: thread safety?

**Review by gadfort — CHANGES_REQUESTED** [review]
@maliberty I think this is alright, but I have some concerns about the timer and thread access. The timers can only be triggered from main thread, failing to do so will cause Qt to generate a bunch of warnings. Additionally , the buffer can be added to and cleared from any number of threads (DRT tends to trigger this a lot), so the buffer needs a mutex to avoid clobbering the information.

Did anyone profile to see what the slow-ness comes from? If I recall correctly, adding HTML vs. plain text to the screen takes a lot longer. Right now all text is added as HTML, it might be worth looking at that before using a buffering solution.

**Comment by maliberty** [comment]
> Did anyone profile to see what the slow-ness comes from? If I recall correctly, adding HTML vs. plain text to the screen takes a lot longer. Right now all text is added as HTML, it might be worth looking at that before using a buffering solution.

@AcKoucher did profile and the time is in event processing as I recall.  I think it will be hard to tell from a profile if plain vs html is the culprit.  We could try it the other way though I suspect that high volume updates will still be an issue if we process them line by line.

**Comment by AcKoucher** [comment]
@gadfort FYI profiling showed that some part of the runtime is due to the html part. However as Matt pointed out, the main problem is processing the events for every single line of text to refresh the GUI. Here's the flame graph for logging 10k lines of text using a .tcl script

image

Without using the GUI it takes around 100ms

File: src/gui/src/scriptWidget.cpp [hunk 7]
```diff
@@ -125,6 +130,18 @@ ScriptWidget::ScriptWidget(QWidget* parent)
   setWidget(container);
 }
 
+// When displaying text in Scripting, processing events in order to
+// ensure the text is visible to the user can considerably slow down
+// the logging, so, for reports, we use a buffer.
+void ScriptWidget::flushReportBufferToOuput()
```
[the remark this answers is not in the document]
Comment (gadfort) [reply src/gui/src/scriptWidget.cpp:136]: rename function, it's misspelled.

[the remark this answers is not in the document]
Comment (AcKoucher) [reply src/gui/src/scriptWidget.cpp:136]: I see now. Thanks.

**Comment by gadfort** [comment]
@AcKoucher thanks. I think the approach will be work, but needs to be modified to be thread safe for Qt.

**Comment by AcKoucher** [comment]
@gadfort Ok! I'll address the review.

File: src/gui/src/scriptWidget.cpp [hunk 8]
```diff
@@ -208,9 +225,19 @@ void ScriptWidget::addLogToOutput(const QString& text, const QColor& color)
...
 
-void ScriptWidget::addReportToOutput(const QString& text)
+bool ScriptWidget::reportTimerIsActive()
+{
+  return report_timer_->isActive();
+}
+
+void ScriptWidget::startReportTimer()
+{
+  report_timer_->start(20 /*ms*/);
```
[the remark this answers is not in the document]
Comment (AcKoucher) [reply src/gui/src/scriptWidget.cpp:235]: I just at 20Hz, it looks lowering more don't have much more impact

File: src/gui/src/scriptWidget.cpp [hunk 9]
```diff
@@ -208,9 +232,14 @@ void ScriptWidget::addLogToOutput(const QString& text, const QColor& color)
...
-void ScriptWidget::addReportToOutput(const QString& text)
+void ScriptWidget::startReportTimer()
+{
+  report_timer_->start(report_display_interval);
+}
+
+void ScriptWidget::addMsgToReportBuffer(const QString& text)
 {
-  addToOutput(text, buffer_msg_);
+  report_buffer_ += text;
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:242]: this will also need a mutex here so different threads don't try to add at the same time.

File: src/gui/src/scriptWidget.cpp [hunk 10]
```diff
@@ -385,8 +414,17 @@ class ScriptWidget::GuiSink : public spdlog::sinks::base_sink<Mutex>
...
 
     if (msg.level == spdlog::level::level_enum::off) {
-      // this comes from a ->report
-      widget_->addReportToOutput(formatted_msg);
+      if (QThread::currentThread() == widget_->thread()) {
+        if (!widget_->report_timer_->isActive()) {
+          widget_->startReportTimer();
+        }
+
+        widget_->addMsgToReportBuffer(formatted_msg);
```
Comment (gadfort) [inline src/gui/src/scriptWidget.cpp:422]: you still need to add the message, you just can't trigger the timer or the event loop. Just move this line up to before the thread check.

**Review by gadfort — CHANGES_REQUESTED** [review]
Looks good, just needs the additional mutex lock and fix the handling of the message when not in the main thread.

**Comment by AcKoucher** [comment]
Fixed. Thanks for the feedback @gadfort !

File: src/gui/src/scriptWidget.cpp [hunk 11]
```diff
@@ -385,8 +415,17 @@ class ScriptWidget::GuiSink : public spdlog::sinks::base_sink<Mutex>
...
+      widget_->addMsgToReportBuffer(formatted_msg);
+
+      if (QThread::currentThread() == widget_->thread()) {
+        if (!widget_->report_timer_->isActive()) {
+          widget_->startReportTimer();
+        }
+
+        // the event loop is blocked so we need to manually process
+        // events so that the timer keeps going
+        QCoreApplication::processEvents(QEventLoop::ExcludeUserInputEvents);
```
Comment (maliberty) [inline src/gui/src/scriptWidget.cpp:427]: Does this mean that the event won't be processed until the main thread get a message?

Comment (gadfort) [reply src/gui/src/scriptWidget.cpp:427]: yes, or the next time the event loop is processed which would be when the main thread is done executing something

**Review by gadfort — APPROVED** [review]
LGTM

**Review by maliberty — APPROVED** [review]
