### PR TITLE
odb: avoid skipping bbox computation for inst when block is not valid

### LINKED ISSUE #4032: zooming into macro with large offset, they disappear from view
### Describe the bug

This is a follow up of #3998.

When zooming in, the contents of macros with large offset disappears from view.

Same behavior whether top references macros for a, b and c or whether it's hierarchical def.

It seems that the "is in view" calculation doesn't properly take offset into account.

### Expected Behavior

Display should always show the macro contents.

### Environment

```shell
v2.0-10398-gecc03c290 Sept 23
M1 compiled with mpl2/par patch
```

### To Reproduce

make or 

and then zoom into macro b or c and you eventually get a blank screen.

[test_origin_hier.tgz](https://github.com/The-OpenROAD-Project/OpenROAD/files/12707685/test_origin_hier.tgz)

### Relevant log output

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Fix #4032

The callback cpp test was considering that, for a created inst whose block has not a valid bbox, calling setOrigin would only be effective in the first call. However, with the fix here, as long as the block has not a valid bbox, every setOrigin call should trigger callback events.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Please look at the odb test failure

File: src/odb/test/cpp/TestCallBacks.cpp [hunk 1]
```diff
@@ -58,11 +58,13 @@ BOOST_AUTO_TEST_CASE(test_inst_and_iterm)
...
   cb->clearEvents();
   i1->setOrigin(100, 100);
-  BOOST_TEST(cb->events.size() == 0);
-  i1->findITerm("a")->connect(n1);
   BOOST_TEST(cb->events.size() == 2);
-  BOOST_TEST(cb->events[0] == "PreConnect iterm to net n1");
-  BOOST_TEST(cb->events[1] == "PostConnect iterm to net n1");
+  BOOST_TEST(cb->events[0] == "PreMove inst i1");
+  BOOST_TEST(cb->events[1] == "PostMove inst i1");
+  i1->findITerm("a")->connect(n1);
```
Comment (maliberty) [inline src/odb/test/cpp/TestCallBacks.cpp:64]: Add a `cb->clearEvents();` before connect to separate events between setOrigin and connect.

**Comment by AcKoucher** [comment]
@maliberty I ran Secure-CI just to be sure that there wouldn't be an problem. It only shows the asap7 aes-block failure which we see on master.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
mac is having IT issues and can be ignored.
