### PR TITLE
Gui timing widget bugfix

### LINKED ISSUE #8396: Timing widget crash when using the 'from' or 'through' list
### Describe the bug

Timing widget crashes if a pin is added to the 'through' list and the update button is pressed. @jeffng-or also reports a crash after adding a pin to the 'from' list. Bisecting over the git history found ff403b375cc4d324935ec0c55455191047387d49 as the first bad commit

### Expected Behavior

No crash

### Environment

```shell
See above
```

### To Reproduce

See above

### Relevant log output

```shell

```

### Screenshots

_No response_

### Additional Context

```
Signal 11 received
Stack trace:
 0# handler(int) in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 2# sta::ExceptionFromTo::~ExceptionFromTo() in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 3# sta::ExceptionFromTo::~ExceptionFromTo() in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 4# sta::ExceptionTo::~ExceptionTo() in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 5# sta::Search::deleteFilteredArrivals() in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 6# gui::STAGuiInterface::getTimingPaths(std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::vector<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>, std::__1::allocator<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>>> const&, std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, sta::Set<sta::Clock*, sta::ClockIndexLess>*) const in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 7# gui::TimingPathsModel::populatePaths(std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::vector<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>, std::__1::allocator<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>>> const&, std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, sta::Set<sta::Clock*, sta::ClockIndexLess>*) in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 8# gui::TimingPathsModel::populateModel(std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::vector<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>, std::__1::allocator<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>>> const&, std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, sta::Set<sta::Clock*, sta::ClockIndexLess>*) in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
 9# gui::TimingWidget::populateAndSortModels(std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::vector<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>, std::__1::allocator<std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>>>> const&, std::__1::set<sta::Pin const*, std::__1::less<sta::Pin const*>, std::__1::allocator<sta::Pin const*>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, sta::Set<sta::Clock*, sta::ClockIndexLess>*) in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
10# gui::TimingWidget::populatePaths() in /Users/pk/repos/openroad-flow-scripts-private/tools/OpenROAD/build/src/openroad
11# void doActivate<false>(QObject*, int, void**) in /nix/store/bg63dhw74nln879jb9wl9l88a7l6clk3-qtbase-5.15.17/lib/libQt5Core.5.15.17.dylib
```

### PR DESCRIPTION
**Pull request by LucasYuki**
Fixes #8396.

The STA::ExceptionFromTo deletes the STA::ClockSet in its destructor, so it's necessary to create a copy of the STA::ClockSet.

### CODE REVIEW

File: src/gui/src/staGuiInterface.cpp [hunk 1]
```diff
@@ -1046,21 +1046,31 @@ TimingPathList STAGuiInterface::getTimingPaths(
...
+    const sta::ClockSet* clks) const
 {
   TimingPathList paths;
 
   initSTA();
 
+  sta::ClockSet* clks_from = nullptr;
+  sta::ClockSet* clks_to = nullptr;
+  if (clks) {
+    clks_from = new sta::ClockSet;
```
Comment (gadfort) [inline src/gui/src/staGuiInterface.cpp:1058]: Does opensta take care of deleting these?

Comment (LucasYuki) [reply src/gui/src/staGuiInterface.cpp:1058]: Yes. STA deleting these sets was the cause of the issue.
