### PR TITLE
mpl2: apply constraint relaxation until we find a reasonable split when using PAR

### LINKED ISSUE #6083: mpl2 recurses itself to a seg fault on BoomFrontend
### Describe the bug

The macro placer runs for 14h before seg faulting on BoomFrontend, which is a sub-module of BoomTile. Note that the segfault isn't seen in the full BoomTile run, which runs for about 1h.

I've re-run the job in GDB and mpl2 is infinitely recursing itself into oblivion. Here's a snippet of the stack trace:

```
 
Thread 1 "openroad" received signal SIGSEGV, Segmentation fault.
0x00007ffff3294c5c in __pthread_create_2_1 (newthread=0x556604b97050, attr=0x0, start_routine=0x7ffff36dc240, arg=0x5566029a42b0) at ./nptl/pthread_create.c:621
621	./nptl/pthread_create.c: No such file or directory.
(gdb) where
#0  0x00007ffff3294c5c in __pthread_create_2_1 (newthread=0x556604b97050, 
    attr=0x0, start_routine=0x7ffff36dc240, arg=0x5566029a42b0)
    at ./nptl/pthread_create.c:621
#1  0x00007ffff36dc329 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000555558597310 in par::KWayFMRefine::InitializeGainBucketsKWay(std::vector<std::shared_ptr<par::PriorityQueue>, std::allocator<std::shared_ptr<par::PriorityQueue> > >&, std::shared_ptr<par::Hypergraph> const&, std::vector<int, std::allocator<int> > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, std::vector<float, std::allocator<float> > const&, std::vector<int, std::allocator<int> > const&) const ()
#3  0x00005555585988ff in par::KWayFMRefine::Pass(std::shared_ptr<par::Hypergraph> const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, std::vector<float, std::allocator<float> >&, std::vector<int, std::allocator<int> >&, std::vector<bool, std::allocator<bool> >&) ()
#4  0x0000555558583528 in par::Refiner::Refine(std::shared_ptr<par::Hypergraph> const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<int, std::allocator<int> >&) ()
#5  0x00005555585775aa in par::MultilevelPartitioner::InitialPartition(std::shared_ptr<par::Hypergraph> const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, int&) const ()
#6  0x000055555857a144 in par::MultilevelPartitioner::SingleLevelPartition(std::shared_ptr<par::Hypergraph> const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&) const ()
#7  0x000055555857a7d4 in par::MultilevelPartitioner::Partition(std::shared_ptr<par::Hypergraph> const&, std::vector<std::vector<float, std::allocator<float> >,--Type <RET> for more, q to quit, c to continue without paging--
#8  0x000055555854860f in par::TritonPart::MultiLevelPartition() ()
#9  0x000055555854a339 in par::TritonPart::PartitionKWaySimpleMode(unsigned int, float, unsigned int, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&) ()
#10 0x000055555853f6e6 in par::PartitionMgr::PartitionKWaySimpleMode(unsigned int, float, unsigned int, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&) ()
#11 0x00005555581ba37c in mpl2::ClusteringEngine::breakLargeFlatCluster(mpl2::Cluster*) ()
#12 0x00005555581ba62b in mpl2::ClusteringEngine::breakLargeFlatCluster(mpl2::Cluster*) ()
#13 0x00005555581ba63a in mpl2::ClusteringEngine::breakLargeFlatCluster(mpl2::Cluster*) ()
...
#11113 0x00005555581bba5b in mpl2::ClusteringEngine::updateSubTree(mpl2::Cluster*) ()
#11114 0x00005555581c45b5 in mpl2::ClusteringEngine::multilevelAutocluster(mpl2::Cluster*) ()
#11115 0x00005555581c4ee7 in mpl2::ClusteringEngine::run() ()
#11116 0x0000555558145a48 in mpl2::HierRTLMP::runMultilevelAutoclustering() ()
```
The full-ish stack trace can be found at: https://drive.google.com/file/d/10MMydy8f761RPeXXE5FKgIVFDAtlWwCn/view?usp=sharing

The tarball can be found at: https://drive.google.com/file/d/1PH8jZAREhRn4NIVryR7pes3sKNGSIBqs/view?usp=sharing

### Expected Behavior

Successful mpl2 run without a seg fault and running less than 1h

### Environment

```shell
commit defc349ec719f45e115b85e317e95db86769e439 (HEAD -> master, origin/master, origin/HEAD)
Merge: e30f8fc8 8c3afb17
Author: Matt Liberty <mliberty@precisioninno.com>
Date:   Mon Oct 28 18:28:51 2024 -0700

    Merge pull request #2520 from Pinata-Consulting/makefile-do-floorplan-fix-2
    
    makefile: fix one more do-floorplan gaffe
```

### To Reproduce

1. unpack the tarball (link in the description)
2. source your ORFS env.sh
3. execute run-me-BoomFrontend-asap7-base.sh

### Relevant log output

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### LINKED ISSUE #6397: rtlmp fails to find solution
### Describe the bug

https://github.com/The-OpenROAD-Project/OpenROAD/pull/6391 seems to triggering on designs that used to pass without any issues.
With this PR I'm getting:
```
[ERROR MPL-0037] Couldn't break flat cluster (root)_glue_logic_0_0 with PAR. The solution is fully unbalanced.
Error: sc_macro_placement.tcl, 115 MPL-0037
```

### Expected Behavior

Macros placed without errors

### Environment

```shell
OpenROAD v2.0-17721-g5f20e5980 
Features included (+) or not (-): +GPU +GUI +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
```

### To Reproduce

[sc_issue_ethmac_job0_skywater130_sky130hd_floorplan.macro_placement0_20241220-034710.tar.gz](https://github.com/user-attachments/files/18205786/sc_issue_ethmac_job0_skywater130_sky130hd_floorplan.macro_placement0_20241220-034710.tar.gz)

```
tar xvf sc_issue_ethmac_job0_skywater130_sky130hd_floorplan.macro_placement0_20241220-034710.tar.gz
cd sc_issue_ethmac_job0_skywater130_sky130hd_floorplan.macro_placement0_20241220-034710
./run.sh
```

### Relevant log output

```shell
Floorplan Outline: (0, 0) (1142.89, 1142.89),  Core Outline: (1.38, 2.72) (1141.72, 1139.68)
	Number of std cell instances: 8017
	Area of std cell instances: 99596.03
	Number of macros: 1
	Area of macros: 419462.72
	Halo width: 40.00
	Halo height: 40.00
	Area of macros with halos: 541366.31
	Area of std cell instances + Area of macros: 519058.75
	Core area: 1296521.00
	Design Utilization: 0.40
	Core Utilization: 0.11
	Manufacturing Grid: 5

[ERROR MPL-0037] Couldn't break flat cluster (root)_glue_logic_0_0 with PAR. The solution is fully unbalanced.
Error: sc_macro_placement.tcl, 115 MPL-0037
```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolve #6397
Resolve #6083

Due to the discrepancy that may exist between the weight of vertices that represent macros/std cells, PAR may fail to meet the balance constraint defined within MPL2. This may cause the output to be completely unbalanced and lead to infinite partitioning recursion.

The changes here are to apply a relaxation to the constraint until we find a reasonable split.

### CODE REVIEW

**Comment by AcKoucher** [comment]
If the approach is ok, I'll run Secure-CI

File: src/mpl2/src/clusterEngine.cpp [hunk 1]
```diff
@@ -1432,33 +1432,39 @@ void ClusteringEngine::breakLargeFlatCluster(Cluster* parent)
...
+    solution = triton_part_->PartitionKWaySimpleMode(num_parts,
+                                                     balance_constraint,
+                                                     seed,
+                                                     hyperedges,
+                                                     vertex_weight,
+                                                     hyperedge_weights);
+
+    balance_constraint += balance_constraint_relaxation_factor;
+  } while (partitionerSolutionIsFullyUnbalanced(solution,
+                                                num_other_cluster_vertices));
```
Comment (gadfort) [inline src/mpl2/src/clusterEngine.cpp:1467]: couldn't this go on forever?

Comment (AcKoucher) [reply src/mpl2/src/clusterEngine.cpp:1467]: I think it may be possible to come up with a case in which it will go on for a very long time. E.g., a cluster with 1 macro and 3 std cells for which we set the max std cell threshold to be 2. It would be quite extreme though.

However if we want some defensive measure we can limit the amount of tries? I'm open to suggestions.

Comment (maliberty) [reply src/mpl2/src/clusterEngine.cpp:1467]: balance_constraint  will eventually become too large to have much meaning.  Probably we should stop at 90%

File: src/mpl2/src/clusterEngine.cpp [hunk 2]
```diff
@@ -1432,33 +1432,44 @@ void ClusteringEngine::breakLargeFlatCluster(Cluster* parent)
...
-      = triton_part_->PartitionKWaySimpleMode(num_parts,
-                                              balance_constraint,
-                                              seed,
-                                              hyperedges,
-                                              vertex_weight,
-                                              hyperedge_weights);
+    if (balance_constraint >= 90) {
+      logger_->error(
+          MPL, 41, "Cannot find a balanced partitioning for the clusters.");
+    }
```
Comment (eder-matheus) [inline src/mpl2/src/clusterEngine.cpp:1461]: @maliberty This covers your comment?

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Error: MPL 0041 used 2 times, next free message id is 45

**Comment by eder-matheus** [comment]
@maliberty I will run a secure-ci before merging this PR. I don't expect changes in there, but I'll do it to ensure nothing will break.
